"""
Tinku Phase 6 — Export Router
Handles PDF and Word document generation from chat content
"""
from fastapi import APIRouter
from fastapi.responses import StreamingResponse, JSONResponse
from pydantic import BaseModel
import io
import re

router = APIRouter()

class ExportRequest(BaseModel):
    content: str
    format: str  # "pdf" or "docx"
    title: str = "Tinku Report"

def clean_markdown(text: str) -> str:
    """Strip markdown symbols for clean document."""
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    text = re.sub(r'\*(.+?)\*', r'\1', text)
    text = re.sub(r'#{1,6}\s+', '', text)
    text = re.sub(r'\[([^\]]+)\]\([^\)]+\)', r'\1', text)
    return text.strip()

def extract_title(content: str) -> str:
    """Extract title from report content."""
    lines = content.strip().split('\n')
    for line in lines[:5]:
        clean = re.sub(r'[#*`]', '', line).strip()
        if len(clean) > 5 and len(clean) < 100:
            return clean
    return "Tinku Report"

@router.post("/export")
async def export_content(data: ExportRequest):
    content = data.content
    title = extract_title(content) if data.title == "Tinku Report" else data.title

    if data.format == "pdf":
        return await generate_pdf(content, title)
    elif data.format == "docx":
        return await generate_docx(content, title)
    else:
        return JSONResponse({"error": "Invalid format"}, status_code=400)

async def generate_pdf(content: str, title: str) -> StreamingResponse:
    """Generate professional PDF using reportlab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                         HRFlowable, PageBreak)
        from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=2.5*cm, rightMargin=2.5*cm,
            topMargin=2.5*cm, bottomMargin=2.5*cm,
            title=title,
            author="Tinku AI"
        )

        # Styles
        styles = getSampleStyleSheet()
        ACCENT = colors.HexColor('#6366f1')
        DARK   = colors.HexColor('#1a1a2e')
        GRAY   = colors.HexColor('#6b7280')
        LIGHT  = colors.HexColor('#f8fafc')

        title_style = ParagraphStyle('TinkuTitle',
            fontSize=22, fontName='Helvetica-Bold',
            textColor=DARK, spaceAfter=6,
            alignment=TA_LEFT, leading=28)

        subtitle_style = ParagraphStyle('TinkuSub',
            fontSize=11, fontName='Helvetica',
            textColor=GRAY, spaceAfter=4,
            alignment=TA_LEFT)

        h1_style = ParagraphStyle('TinkuH1',
            fontSize=15, fontName='Helvetica-Bold',
            textColor=ACCENT, spaceBefore=18, spaceAfter=8,
            leading=20)

        h2_style = ParagraphStyle('TinkuH2',
            fontSize=12, fontName='Helvetica-Bold',
            textColor=DARK, spaceBefore=12, spaceAfter=6,
            leading=16)

        body_style = ParagraphStyle('TinkuBody',
            fontSize=10, fontName='Helvetica',
            textColor=colors.HexColor('#374151'),
            spaceAfter=8, leading=16,
            alignment=TA_JUSTIFY)

        bullet_style = ParagraphStyle('TinkuBullet',
            fontSize=10, fontName='Helvetica',
            textColor=colors.HexColor('#374151'),
            spaceAfter=5, leading=16,
            leftIndent=16, bulletIndent=0,
            bulletFontName='Helvetica', bulletFontSize=10)

        story = []

        # Header
        story.append(Paragraph(title, title_style))
        story.append(Paragraph("Generated by Tinku AI Agent", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=2, color=ACCENT, spaceAfter=16))

        # Parse content
        lines = content.split('\n')
        for line in lines:
            stripped = line.strip()
            if not stripped:
                story.append(Spacer(1, 6))
                continue

            # H1
            if stripped.startswith('## ') or stripped.startswith('# '):
                text = re.sub(r'^#{1,3}\s+', '', stripped)
                text = re.sub(r'[*`]', '', text)
                story.append(Paragraph(text, h1_style))

            # H2
            elif stripped.startswith('### ') or stripped.startswith('#### '):
                text = re.sub(r'^#{3,6}\s+', '', stripped)
                text = re.sub(r'[*`]', '', text)
                story.append(Paragraph(text, h2_style))

            # Bullet
            elif stripped.startswith(('* ', '- ', '• ')):
                text = stripped[2:].strip()
                text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
                text = re.sub(r'[*`]', '', text)
                story.append(Paragraph(f'• {text}', bullet_style))

            # Numbered list
            elif re.match(r'^\d+\.\s', stripped):
                text = re.sub(r'^\d+\.\s+', '', stripped)
                text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
                story.append(Paragraph(text, bullet_style))

            # HR
            elif stripped in ('---', '***', '___'):
                story.append(HRFlowable(width="100%", thickness=0.5,
                                        color=colors.HexColor('#e5e7eb'), spaceAfter=8))
            # Body
            else:
                text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', stripped)
                text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)
                text = re.sub(r'`(.+?)`', r'<font name="Courier">\1</font>', text)
                text = text.replace('&', '&amp;').replace('<b>', '<b>').replace('</b>', '</b>')
                try:
                    story.append(Paragraph(text, body_style))
                except:
                    story.append(Paragraph(clean_markdown(stripped), body_style))

        # Footer note
        story.append(Spacer(1, 20))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                color=colors.HexColor('#e5e7eb'), spaceAfter=8))
        story.append(Paragraph("Tinku AI Agent • tinku-test-v2.onrender.com",
                               subtitle_style))

        doc.build(story)
        buffer.seek(0)

        return StreamingResponse(
            buffer,
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="tinku_report.pdf"'}
        )

    except Exception as e:
        return JSONResponse({"error": f"PDF generation failed: {str(e)}"}, status_code=500)


async def generate_docx(content: str, title: str) -> StreamingResponse:
    """Generate professional Word document using python-docx."""
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches, Cm
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
        import re

        doc = Document()

        # Page margins
        for section in doc.sections:
            section.top_margin = Cm(2.5)
            section.bottom_margin = Cm(2.5)
            section.left_margin = Cm(2.5)
            section.right_margin = Cm(2.5)

        # Title
        t = doc.add_heading(title, 0)
        t.runs[0].font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)
        t.runs[0].font.size = Pt(22)

        # Subtitle
        sub = doc.add_paragraph("Generated by Tinku AI Agent")
        sub.runs[0].font.color.rgb = RGBColor(0x6b, 0x72, 0x80)
        sub.runs[0].font.size = Pt(10)
        sub.runs[0].font.italic = True

        # Separator
        doc.add_paragraph("─" * 60)

        # Parse content
        lines = content.split('\n')
        for line in lines:
            stripped = line.strip()
            if not stripped:
                doc.add_paragraph()
                continue

            if stripped.startswith('## ') or stripped.startswith('# '):
                text = re.sub(r'^#{1,3}\s+', '', stripped)
                text = re.sub(r'[*`]', '', text)
                h = doc.add_heading(text, level=1)
                h.runs[0].font.color.rgb = RGBColor(0x63, 0x66, 0xf1)

            elif stripped.startswith('### '):
                text = re.sub(r'^#{3,6}\s+', '', stripped)
                text = re.sub(r'[*`]', '', text)
                h = doc.add_heading(text, level=2)
                h.runs[0].font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)

            elif stripped.startswith(('* ', '- ', '• ')):
                text = stripped[2:].strip()
                text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
                text = re.sub(r'[*`]', '', text)
                p = doc.add_paragraph(style='List Bullet')
                p.add_run(text).font.size = Pt(10)

            elif re.match(r'^\d+\.\s', stripped):
                text = re.sub(r'^\d+\.\s+', '', stripped)
                text = re.sub(r'[*`]', '', text)
                p = doc.add_paragraph(style='List Number')
                p.add_run(text).font.size = Pt(10)

            elif stripped in ('---', '***', '___'):
                doc.add_paragraph("─" * 60)

            else:
                text = re.sub(r'[*`#]', '', stripped)
                p = doc.add_paragraph()
                p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
                run = p.add_run(text)
                run.font.size = Pt(10)
                run.font.color.rgb = RGBColor(0x37, 0x41, 0x51)

        # Footer
        doc.add_paragraph("─" * 60)
        footer = doc.add_paragraph("Tinku AI Agent • tinku-test-v2.onrender.com")
        footer.runs[0].font.size = Pt(9)
        footer.runs[0].font.color.rgb = RGBColor(0x6b, 0x72, 0x80)
        footer.runs[0].font.italic = True

        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)

        return StreamingResponse(
            buffer,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": 'attachment; filename="tinku_report.docx"'}
        )

    except Exception as e:
        return JSONResponse({"error": f"DOCX generation failed: {str(e)}"}, status_code=500)


# ═══════════════════════════════════════════════
# RESUME BUILDER ENDPOINT
# ═══════════════════════════════════════════════
from resume_builder import build_resume_pdf as _build_pdf, build_resume_docx as _build_docx

class ResumeRequest(BaseModel):
    data: dict
    format: str  # "pdf" or "docx"

@router.post("/resume")
async def build_resume(req: ResumeRequest):
    d = req.data
    name        = d.get('name', 'Your Name')
    title       = d.get('title', 'Professional')
    email       = d.get('email', '')
    phone       = d.get('phone', '')
    skills      = d.get('skills', '')
    experience  = d.get('experience', '')
    education   = d.get('education', '')
    achievements = d.get('achievements', '')

    if req.format == 'pdf':
        return await generate_resume_pdf(name, title, email, phone,
                                         skills, experience, education, achievements)
    else:
        return await generate_resume_docx(name, title, email, phone,
                                          skills, experience, education, achievements)

async def generate_resume_pdf(name, title, email, phone,
                               skills, experience, education, achievements):
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle)
        from reportlab.lib.enums import TA_LEFT, TA_CENTER

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4,
            leftMargin=2*cm, rightMargin=2*cm,
            topMargin=2*cm, bottomMargin=2*cm)

        ACCENT = colors.HexColor('#6366f1')
        DARK   = colors.HexColor('#111827')
        GRAY   = colors.HexColor('#6b7280')
        WHITE  = colors.white

        name_style = ParagraphStyle('Name', fontSize=26,
            fontName='Helvetica-Bold', textColor=WHITE,
            alignment=TA_LEFT, leading=32)
        title_style = ParagraphStyle('Title', fontSize=13,
            fontName='Helvetica', textColor=colors.HexColor('#c7d2fe'),
            alignment=TA_LEFT, spaceAfter=4)
        contact_style = ParagraphStyle('Contact', fontSize=9,
            fontName='Helvetica', textColor=colors.HexColor('#e0e7ff'),
            alignment=TA_LEFT)
        section_style = ParagraphStyle('Section', fontSize=12,
            fontName='Helvetica-Bold', textColor=ACCENT,
            spaceBefore=14, spaceAfter=6)
        body_style = ParagraphStyle('Body', fontSize=10,
            fontName='Helvetica', textColor=DARK,
            spaceAfter=5, leading=15)

        story = []

        # Header block with accent background
        header_data = [[
            Paragraph(name, name_style),
        ]]
        header_table = Table(header_data, colWidths=[17*cm])
        header_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), ACCENT),
            ('PADDING', (0,0), (-1,-1), 16),
            ('ROUNDEDCORNERS', [8]),
        ]))
        story.append(header_table)
        story.append(Spacer(1, 4))

        # Contact row
        contact_info = []
        if email: contact_info.append(f"✉ {email}")
        if phone: contact_info.append(f"📞 {phone}")
        contact_str = "  |  ".join(contact_info) if contact_info else ""

        info_data = [[
            Paragraph(title, ParagraphStyle('T2', fontSize=12,
                fontName='Helvetica-Bold', textColor=DARK)),
            Paragraph(contact_str, ParagraphStyle('C2', fontSize=9,
                fontName='Helvetica', textColor=GRAY, alignment=2))
        ]]
        info_table = Table(info_data, colWidths=[9*cm, 8*cm])
        info_table.setStyle(TableStyle([
            ('PADDING', (0,0), (-1,-1), 6),
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8faff')),
            ('ROUNDEDCORNERS', [6]),
        ]))
        story.append(info_table)
        story.append(Spacer(1, 10))

        def add_section(heading, content):
            if not content or content.lower() == 'none': return
            story.append(Paragraph(heading, section_style))
            story.append(HRFlowable(width="100%", thickness=1,
                                    color=ACCENT, spaceAfter=6))
            # Split bullet items
            for line in content.split(','):
                line = line.strip()
                if line:
                    story.append(Paragraph(f"• {line}", body_style))

        def add_section_full(heading, content):
            if not content or content.lower() == 'none': return
            story.append(Paragraph(heading, section_style))
            story.append(HRFlowable(width="100%", thickness=1,
                                    color=ACCENT, spaceAfter=6))
            story.append(Paragraph(content, body_style))

        add_section("SKILLS", skills)
        add_section_full("EXPERIENCE", experience)
        add_section_full("EDUCATION", education)
        add_section("ACHIEVEMENTS", achievements)

        # Footer
        story.append(Spacer(1, 20))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                color=colors.HexColor('#e5e7eb')))
        story.append(Paragraph("Resume generated by Tinku AI",
            ParagraphStyle('Footer', fontSize=8, textColor=GRAY,
                           alignment=TA_CENTER, spaceBefore=6)))

        doc.build(story)
        buffer.seek(0)
        return StreamingResponse(buffer, media_type="application/pdf",
            headers={"Content-Disposition": 'attachment; filename="resume.pdf"'})

    except Exception as e:
        return JSONResponse({"error": str(e)}, status_code=500)


async def generate_resume_docx(name, title, email, phone,
                                skills, experience, education, achievements):
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Cm
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()
        for section in doc.sections:
            section.top_margin = Cm(2)
            section.bottom_margin = Cm(2)
            section.left_margin = Cm(2)
            section.right_margin = Cm(2)

        # Name
        h = doc.add_heading(name, 0)
        h.runs[0].font.size = Pt(24)
        h.runs[0].font.color.rgb = RGBColor(0x63, 0x66, 0xf1)

        # Title + contact
        sub = doc.add_paragraph()
        sub.add_run(title).font.bold = True
        if email or phone:
            contact = []
            if email: contact.append(email)
            if phone: contact.append(phone)
            sub.add_run(f"  |  " + "  |  ".join(contact)).font.color.rgb = RGBColor(0x6b, 0x72, 0x80)

        doc.add_paragraph("─" * 60)

        def add_section(heading, content):
            if not content or content.lower() == 'none': return
            h2 = doc.add_heading(heading, level=1)
            h2.runs[0].font.color.rgb = RGBColor(0x63, 0x66, 0xf1)
            h2.runs[0].font.size = Pt(12)
            for item in content.split(','):
                item = item.strip()
                if item:
                    p = doc.add_paragraph(style='List Bullet')
                    p.add_run(item).font.size = Pt(10)

        def add_section_full(heading, content):
            if not content or content.lower() == 'none': return
            h2 = doc.add_heading(heading, level=1)
            h2.runs[0].font.color.rgb = RGBColor(0x63, 0x66, 0xf1)
            h2.runs[0].font.size = Pt(12)
            p = doc.add_paragraph(content)
            p.runs[0].font.size = Pt(10)

        add_section("SKILLS", skills)
        add_section_full("EXPERIENCE", experience)
        add_section_full("EDUCATION", education)
        add_section("ACHIEVEMENTS", achievements)

        doc.add_paragraph("─" * 60)
        footer = doc.add_paragraph("Resume generated by Tinku AI")
        footer.runs[0].font.size = Pt(8)
        footer.runs[0].font.color.rgb = RGBColor(0x6b, 0x72, 0x80)
        footer.runs[0].font.italic = True

        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return StreamingResponse(buffer,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": 'attachment; filename="resume.docx"'})

    except Exception as e:
        return JSONResponse({"error": str(e)}, status_code=500)
